#!/usr/bin/env python

import os,sys

# determine the directory where this script resides, from this, we'll
# make lotsa assumptions
script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
interface_directory = "impl/packages/chromeless/data"
ui_directory = os.path.join(script_dir, "ui")

# now because this is a demo, and lloyd is an idiot, we'll just
# symlink user interface files from ui into the bowels of packages
# where the app-kit main file lives
if os.path.lexists(interface_directory):
    if not os.path.islink(interface_directory):
        raise interface_directory + " exists and is not a symlink.  please remove that bugger"
else:
    os.symlink(ui_directory, interface_directory)


browserToLaunch = "test_require/index.html" 
browserToLaunch = "first_browser/index.html" 
try: 
   browserToLaunch = sys.argv[1]
except: 
   pass 

print "Will open the browser script ="+ browserToLaunch

# now let's run the cfx thingy and specify the app-kit main module
# as our starting point
os.system("impl/bin/cfx -a xulrunner --static-args {\\\"browser\\\":\\\""+ browserToLaunch+"\\\"} -p \"impl/packages/chromeless\" run")
