#!/usr/bin/env python

import os,sys,shutil


cuddlefish_root = os.path.dirname(os.path.abspath(sys.argv[0]))

if 'CUDDLEFISH_ROOT' not in os.environ:
    os.environ['CUDDLEFISH_ROOT'] = cuddlefish_root

# add our own python-lib path to the python module search path.
python_lib_dir = os.path.join(cuddlefish_root, "impl")
if python_lib_dir not in sys.path:
    sys.path.append(python_lib_dir)


import cuddlefish
import simplejson as json

cuddlefish.run([
        "test",
        "-a", "xulrunner",
        "-b", "./build/xulrunner-sdk/bin/xulrunner-bin",
        "--static-args", json.dumps({"browser": "./examples/dragdrop/index.html"}),
        "--templatedir", "./app-extension-for-tests",
        "--pkgdir", "packages/chromeless"
        ])


