#!/usr/bin/env python

# Helper script to install the app with XULRunner. 
# It turns out XULRunner wants a full path! 

import os,sys
from subprocess import call

cur_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
cur_dir = os.path.join(cur_dir,"build","xulrunner-sdk","bin","xulrunner-bin");

chromeless_zip_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
chromeless_zip_dir = os.path.join(chromeless_zip_dir,"chromeless.zip");

os.system(cur_dir+" --install-app "+chromeless_zip_dir);

print cur_dir
print chromeless_zip_dir
